name: Flask Static Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    # 1. 检出代码
    - name: Checkout 🛎️
      uses: actions/checkout@v4

    # 2. 设置Python环境
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # 3. 安装依赖和冻结应用
    - name: Install dependencies & freeze Flask 🔧
      run: |
        pip install -r requirements.txt
        pip install frozen-flask
        python freeze.py  # 执行静态生成脚本

    # 4. 部署到gh-pages
    - name: Deploy to GitHub Pages 🚀
      uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        branch: gh-pages       # 目标分支
        folder: build          # Frozen-Flask默认输出目录
        clean: true            # 部署前清空目标分支内容
        token: ${{ secrets.GITHUB_TOKEN }}
